// Country and timezone data for forms
// This provides a mapping of countries to their primary timezones

export const COUNTRIES = [
  { name: 'Argentina', timezone: 'UTC-03:00 (Buenos Aires, São Paulo)' },
  { name: 'Australia', timezone: 'UTC+10:00 (Sydney, Melbourne)' },
  { name: 'Austria', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'Belgium', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'Brazil', timezone: 'UTC-03:00 (Buenos Aires, São Paulo)' },
  { name: 'Canada', timezone: 'UTC-05:00 (Eastern Time - US & Canada)' },
  { name: 'Chile', timezone: 'UTC-03:00 (Buenos Aires, São Paulo)' },
  { name: 'Colombia', timezone: 'UTC-05:00 (Eastern Time - US & Canada)' },
  { name: 'Czech Republic', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'Denmark', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'Finland', timezone: 'UTC+02:00 (Athens, Cairo, Jerusalem)' },
  { name: 'France', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'Germany', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'Greece', timezone: 'UTC+02:00 (Athens, Cairo, Jerusalem)' },
  { name: 'India', timezone: 'UTC+05:30 (Mumbai, New Delhi)' },
  { name: 'Ireland', timezone: 'UTC+00:00 (London, Dublin, Lisbon)' },
  { name: 'Israel', timezone: 'UTC+02:00 (Athens, Cairo, Jerusalem)' },
  { name: 'Italy', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'Japan', timezone: 'UTC+09:00 (Tokyo, Seoul)' },
  { name: 'Mexico', timezone: 'UTC-06:00 (Central Time - US & Canada)' },
  { name: 'Netherlands', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'New Zealand', timezone: 'UTC+12:00 (Auckland, Fiji)' },
  { name: 'Norway', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'Poland', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'Portugal', timezone: 'UTC+00:00 (London, Dublin, Lisbon)' },
  { name: 'Saudi Arabia', timezone: 'UTC+03:00 (Moscow, Istanbul)' },
  { name: 'Singapore', timezone: 'UTC+08:00 (Singapore, Beijing, Hong Kong)' },
  { name: 'South Africa', timezone: 'UTC+02:00 (Athens, Cairo, Jerusalem)' },
  { name: 'South Korea', timezone: 'UTC+09:00 (Tokyo, Seoul)' },
  { name: 'Spain', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'Sweden', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'Switzerland', timezone: 'UTC+01:00 (Paris, Berlin, Rome)' },
  { name: 'United Arab Emirates', timezone: 'UTC+04:00 (Dubai, Abu Dhabi)' },
  { name: 'United Kingdom', timezone: 'UTC+00:00 (London, Dublin, Lisbon)' },
  { name: 'United States', timezone: 'UTC-05:00 (Eastern Time - US & Canada)' },
  { name: 'Other', timezone: '' },
];

export const TIMEZONES = [
  'UTC-12:00 (Baker Island)',
  'UTC-11:00 (American Samoa)',
  'UTC-10:00 (Hawaii)',
  'UTC-09:00 (Alaska)',
  'UTC-08:00 (Pacific Time - US & Canada)',
  'UTC-07:00 (Mountain Time - US & Canada)',
  'UTC-06:00 (Central Time - US & Canada)',
  'UTC-05:00 (Eastern Time - US & Canada)',
  'UTC-04:00 (Atlantic Time - Canada)',
  'UTC-03:00 (Buenos Aires, São Paulo)',
  'UTC-02:00 (Mid-Atlantic)',
  'UTC-01:00 (Azores)',
  'UTC+00:00 (London, Dublin, Lisbon)',
  'UTC+01:00 (Paris, Berlin, Rome)',
  'UTC+02:00 (Athens, Cairo, Jerusalem)',
  'UTC+03:00 (Moscow, Istanbul)',
  'UTC+04:00 (Dubai, Abu Dhabi)',
  'UTC+05:00 (Islamabad, Karachi)',
  'UTC+05:30 (Mumbai, New Delhi)',
  'UTC+06:00 (Dhaka, Almaty)',
  'UTC+07:00 (Bangkok, Jakarta)',
  'UTC+08:00 (Singapore, Beijing, Hong Kong)',
  'UTC+09:00 (Tokyo, Seoul)',
  'UTC+10:00 (Sydney, Melbourne)',
  'UTC+11:00 (Solomon Islands)',
  'UTC+12:00 (Auckland, Fiji)',
];

// Industry options for filtering
export const INDUSTRIES = [
  'Technology & Software',
  'Healthcare & Medical',
  'Finance & Banking',
  'E-commerce & Retail',
  'Education & Training',
  'Marketing & Advertising',
  'Real Estate',
  'Manufacturing',
  'Hospitality & Tourism',
  'Transportation & Logistics',
  'Media & Entertainment',
  'Legal Services',
  'Consulting',
  'Construction',
  'Agriculture',
  'Energy & Utilities',
  'Telecommunications',
  'Automotive',
  'Aerospace & Defense',
  'Non-Profit & NGO',
  'Government',
  'Other',
];

// Helper function to get timezone for a country
export function getTimezoneForCountry(countryName: string): string {
  const country = COUNTRIES.find(c => c.name === countryName);
  return country?.timezone || '';
}
