export const JOB_CATEGORIES = [
  'Development & IT',
  'Design & Creative',
  'Writing & Content',
  'Sales & Marketing',
  'Admin & Customer Support',
  'Finance & Accounting',
  'Engineering & Architecture',
  'Data Science & Analytics',
  'IT, Networking & Cybersecurity',
  'AI & Emerging Technologies',
];

export const JOB_SKILL_GROUPS = [
  {
    category: 'Web, Mobile & Software Development',
    skills: [
      'Front-End Development',
      'Back-End Development',
      'Full-Stack Development',
      'WordPress Development',
      'Shopify Development',
      'React.js',
      'Vue.js',
      'Angular',
      'Node.js',
      'PHP',
      'Laravel',
      'Django',
      'Flutter',
      'React Native',
      'iOS Development',
      'Android Development',
      'API Development',
      'Database Design',
      'MySQL',
      'PostgreSQL',
      'MongoDB',
      'DevOps',
      'AWS',
      'Docker',
      'Kubernetes',
      'Web Security',
      'Performance Optimization',
      'Automation Scripting',
    ],
  },
  {
    category: 'Design & Creative',
    skills: [
      'Graphic Design',
      'Logo Design',
      'UI/UX Design',
      'Web Design',
      'Figma',
      'Adobe XD',
      'Adobe Photoshop',
      'Illustrator',
      'Video Editing',
      'Motion Graphics',
      '3D Modeling',
      '2D Animation',
      '3D Animation',
      'Brand Identity Design',
      'Presentation Design',
      'Print Design',
      'Packaging Design',
      'Photo Editing',
      'Illustration',
    ],
  },
  {
    category: 'Writing, Content & Translation',
    skills: [
      'Copywriting',
      'Content Writing',
      'Blog Writing',
      'Technical Writing',
      'Creative Writing',
      'SEO Writing',
      'Proofreading',
      'Editing',
      'Ghostwriting',
      'Grant Writing',
      'Scriptwriting',
      'Transcription',
      'Translation',
      'Subtitling',
      'Academic Writing',
    ],
  },
  {
    category: 'Sales & Marketing',
    skills: [
      'Digital Marketing',
      'Social Media Marketing',
      'Search Engine Optimization (SEO)',
      'Search Engine Marketing (SEM)',
      'Email Marketing',
      'Content Marketing',
      'Affiliate Marketing',
      'Influencer Marketing',
      'Pay-Per-Click Advertising (PPC)',
      'Facebook Ads',
      'Google Ads',
      'Lead Generation',
      'Brand Strategy',
      'Marketing Automation',
      'CRM Management',
    ],
  },
  {
    category: 'Data Science & Analytics',
    skills: [
      'Data Analysis',
      'Data Visualization',
      'Machine Learning',
      'Artificial Intelligence (AI)',
      'Python',
      'R Programming',
      'SQL',
      'Power BI',
      'Tableau',
      'Big Data',
      'Data Cleaning',
      'Predictive Analytics',
      'Deep Learning',
      'Business Intelligence',
      'Statistical Modeling',
    ],
  },
  {
    category: 'Admin Support & Customer Service',
    skills: [
      'Virtual Assistance',
      'Data Entry',
      'Customer Support',
      'Email Support',
      'Chat Support',
      'Technical Support',
      'Project Management',
      'Scheduling',
      'CRM Data Management',
      'Order Processing',
      'Internet Research',
      'Community Management',
      'Documentation',
    ],
  },
  {
    category: 'Accounting & Finance',
    skills: [
      'Accounting',
      'Bookkeeping',
      'Financial Analysis',
      'Tax Preparation',
      'Payroll Management',
      'Budgeting',
      'Financial Forecasting',
      'QuickBooks',
      'Excel Financial Modeling',
      'Auditing',
    ],
  },
  {
    category: 'IT, Networking & Cybersecurity',
    skills: [
      'System Administration',
      'Network Administration',
      'Cybersecurity',
      'Cloud Computing',
      'IT Support',
      'Database Administration',
      'Server Configuration',
      'Troubleshooting',
      'VPN Setup',
      'Firewall Management',
    ],
  },
  {
    category: 'Engineering & Architecture',
    skills: [
      'AutoCAD',
      'Civil Engineering',
      'Mechanical Engineering',
      'Electrical Engineering',
      'Structural Design',
      '3D Rendering',
      'Product Design',
      'CAD Drafting',
      'Blueprint Design',
      'Architecture Visualization',
    ],
  },
  {
    category: 'AI & Emerging Technologies',
    skills: [
      'Chatbot Development',
      'Prompt Engineering',
      'AI Model Integration',
      'Natural Language Processing (NLP)',
      'Computer Vision',
      'Speech Recognition',
      'Generative AI',
      'OpenAI API Integration',
      'TensorFlow',
      'PyTorch',
    ],
  },
];

export const ALL_JOB_SKILLS = Array.from(
  new Set(JOB_SKILL_GROUPS.flatMap(group => group.skills))
).sort((a, b) => a.localeCompare(b));
